### ISSUE TITLE
AHN download fails if the full path `/data/pointcloud/AHN4/as_downloaded/LAZ` does not already exist

### ISSUE THREAD

**Issue by Ylannl** [3DBAG/3dbag-pipeline#9]
I only created the path `/data/pointcloud/AHN4/as_downloaded` (without the `LAZ` dir) and this resulted in all AHN files getting downloaded with the filename 'LAZ' and errors.

**Comment by GinaStavropoulou** [comment]
I added these mkdir commands  in a previous PR so this should solve the problem 

https://github.com/3DBAG/3dbag-pipeline/blob/fc3c0ab0bd97ba8e72ff14062ce588291c0e2df5/packages/core/src/bag3d/core/assets/ahn/download.py#L150

https://github.com/3DBAG/3dbag-pipeline/blob/fc3c0ab0bd97ba8e72ff14062ce588291c0e2df5/packages/core/src/bag3d/core/assets/ahn/download.py#L206

https://github.com/3DBAG/3dbag-pipeline/blob/fc3c0ab0bd97ba8e72ff14062ce588291c0e2df5/packages/core/src/bag3d/core/assets/ahn/download.py#L263
